### ISSUE TITLE
manager port allocation: automate it for high user ids

### ISSUE THREAD

**Issue by muffato** [VertebrateResequencing/wr#398] opened 2021-03-26 12:59 UTC
Hi,

When starting `wr` with no specific configuration, it is unable to find some port numbers for me
```
$ ./wr cloud deploy
EROR[03-10|12:38:39] Could not calculate a suitable unique port number for you, since your user id is so large; please manually set your manager_port and manager_web config options. caller=config.go:424
```
My user ID is indeed quite large (>20,000) and since port numbers are 16 bits only, the allocator can only cope with user IDs up to ~16K: https://github.com/VertebrateResequencing/wr/blob/master/internal/config.go#L417-L426

The fact is that all user IDs at the Sanger are now that high, so no one who joined in the last few years is able to use the automatic port allocation as it is. My suggestion is to either acknowledge that and amend the instructions to explain users how to select port numbers themselves, or change the allocator to, for instance, pick a random port number that is not yet used.

PS: this is wr v0.23.3

**Comment by sb10** [comment] 2021-03-26 13:34
Hi, thanks for the report.

I think the reason it was designed to have this fixed port range per user was so that your ports would always be the same and you could eg. bookmark the web interface and set up particular port forwarding. It also helps prevent you accidentally running multiple managers at once. All while avoiding conflicts with other wr users.

Clients also need to know what port to try and connect to, but when using a random port this could in theory be worked around by storing the used ports on disk and have clients read it from there.

I think a solution that might work is to keep the current system for users < id ~16k, and for users with higher ids to suggest some ports that are available at that time, and write them to the config file for you. Then you'll always use those ports in the future.

There's a complication of what happens if someone else manages to get suggested the same ports, so I can look in to if the error messaging around ports unavailable is clear enough.

Does this sound like a good solution?

**Comment by muffato** [comment] 2021-03-26 13:42
Hi Sendu,

Your explanations are very sensible. Yes, I think it's a good suggestion.

**Comment by sb10** [comment] 2021-03-26 13:46
Ok, this is quite easy to implement, so it should be in the next release of wr. In the mean time, has the documentation been good enough that you've been able to configure your desired ports and get started?

**Comment by muffato** [comment] 2021-03-26 13:56
I can't remember exactly how I found the solution, but I didn't take long to find. I did:
```env WR_MANAGERPORT=11320 WR_MANAGERWEB321 wr cloud deploy```

**Comment by sb10** [comment] 2021-04-29 11:16
This will be in the next release (which should be out tomorrow).

**Closed by sb10** 2021-04-29 11:16 UTC
Labels: enhancement
